[package]
name = "slmp"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["brkp <brkp@tutanota.com>"]
repository = "https://github.com/brkp/slmp-rs"
description = "Pure Rust SLMP client crate"

[dependencies]
enum-primitive-derive = "0.2.2"
num-traits = "0.2.15"
